Fix prefix repetitions for multiline tables
Also add option -z for anonymizing keys with "00"-bytes instead of "??".

diff --git a/dmcrypt-table-keyfield-anonymizer b/dmcrypt-table-keyfield-anonymizer
--- a/dmcrypt-table-keyfield-anonymizer
+++ b/dmcrypt-table-keyfield-anonymizer
@@ -4,13 +4,25 @@
 # hexadecimal key fields with "?"-strings of the same length. This allows to
 # display the contents of those tables without also displaying the keys.
 #
-# v2023.279.1
+# v2023.279.2
 
 set -e
+trap 'test $? = 0 || echo "\"$0\" failed!" >& 2' 0
+
+rchar='?'
+while getopts z opt
+do
+	case $opt in
+		z) rchar=0;;
+		*) false || exit
+	esac
+done
+shift `expr $OPTIND - 1 || :`
+
 # Check whether awk is modern enough and supports named RegEx classes.
 echo 9aA | awk '!/^[[:xdigit:]]+$/ {exit system("false")}'
 
-awk -f /dev/fd/5 5<< 'EO_AWK' -- ${1+"$@"}
+awk -v rchar="$rchar" -f /dev/fd/5 5<< 'EO_AWK' -- ${1+"$@"}
 
 BEGIN {
 	if (annotate = ARGC > 1) {
@@ -21,7 +33,8 @@ BEGIN {
 annotate && FNR == 1 { print "# File \"" FILENAME "\":" >> "/dev/stderr" }
 
 $3 == "crypt" && $5 ~ /^[[:xdigit:]]+$/ {
-	for (i = length($5); i--; ) o = o "?"
+	o = ""
+	for (i = length($5); i--; ) o = o rchar
 	$5 = o
 }
 
