Isolate non-portable commands into new function
The current version of the script uses GNU/BusyBox extensions of the
chmod/chown commands which are not standardized by POSIX.

This makes it easier to replace the functionality with a more portable
implementation later.

diff --git a/inplace b/inplace
--- a/inplace
+++ b/inplace
@@ -1,7 +1,7 @@
 #! /bin/sh
 exit_version() {
 	wr -s << EOF;  exit
-$APP version 2018.201.1
+$APP version 2018.201.2
 
 Copyright (c) 2018 Guenther Brunthaler. All rights reserved.
 
@@ -271,6 +271,19 @@ create_NF() {
 	NF=`mktemp -- "$file"-new.XXXXXXXXXX`
 }
 
+# Try to set new instance file $2 to the same the attributes as original file
+# $1.
+reconcile_attrs() {
+	chown --reference="$1" -- "$2" \
+		|| warn "Could not set owner" \
+			"for new instance" \
+			"of file '$1' (ignored)!"
+	chmod --reference="$1" -- "$2" \
+		|| warn "Could not set permissions" \
+			"for new instance" \
+			"of file '$1' (ignored)!"
+}
+
 fps=0
 while IFS= read -r file
 do
@@ -312,14 +325,7 @@ do
 					"filtered contents as intermediate" \
 					"new file '$NF'!"
 			fi
-			chown --reference="$file" -- "$NF" \
-				|| warn "Could not set owner" \
-					"for new instance" \
-					"of file '$file' (ignored)!"
-			chmod --reference="$file" -- "$NF" \
-				|| warn "Could not set permissions" \
-					"for new instance" \
-					"of file '$file' (ignored)!"
+			reconcile_attrs "$file" "$NF"
 			if mv -- "$NF" "$file"
 			then
 				NF=
