Fix numerous conditional resource leaks
A lot of scripts forgot to trap SIGINT for cleaning up resources
scheduled by the EXIT trap.

diff --git a/jpeg-strip-all-metadata b/jpeg-strip-all-metadata
--- a/jpeg-strip-all-metadata
+++ b/jpeg-strip-all-metadata
@@ -1,9 +1,8 @@
 #! /bin/sh
 exit_version() {
 	wr -s << .; exit
-$APP version 2016.282
-
-Copyright (c) 2015-2016 Guenther Brunthaler. All rights reserved.
+$APP version 2023.211
+Copyright (c) 2015-2023 Guenther Brunthaler. All rights reserved.
 
 This script is free software.
 Distribution is permitted under the terms of the GPLv3.
@@ -67,11 +66,12 @@ fi
 set -e
 cleanup() {
 	rc=$?
-	test -n "$T" && rm -- "$T"
-	test $rc = 0 || echo "$APP failed!" >& 2
+	test "$T" && rm -- "$T"
+	test $rc = 0 || echo "\"$APP\" failed!" >& 2
 }
 T=
 trap cleanup 0
+trap 'exit $?' HUP INT TERM QUIT
 verbose=true
 opts=
 while getopts qDhV opt
@@ -85,7 +85,7 @@ do
 	esac
 done
 shift `expr $OPTIND - 1 || :`
-T=`mktemp "${TMPDIR:-/tmp}/$APP".XXXXXXXXXX`
+T=`mktemp -- "${TMPDIR:-/tmp}/$APP".XXXXXXXXXX`
 for f
 do
 	jpegtran$opts -optimize -copy none -perfect "$f" > "$T"
diff --git a/qr-display-text-as-multiple-codes b/qr-display-text-as-multiple-codes
--- a/qr-display-text-as-multiple-codes
+++ b/qr-display-text-as-multiple-codes
@@ -1,4 +1,5 @@
 #! /bin/sh
+# v2023.211
 QR_BYTES_MAX=190
 QR_WANTS_CODEPAGE=WINDOWS-1252
 SEPARATOR_CHAR='-'
@@ -9,9 +10,8 @@ set -e
 
 exit_version() {
 	wr -s <<- EOF; exit
-	$APP version 2017.356
-
-	Copyright (c) 2015-2017 Guenther Brunthaler. All rights reserved.
+	$APP version 2023.211
+	Copyright (c) 2015-2023 Guenther Brunthaler. All rights reserved.
 
 	This script is free software.
 	Distribution is permitted under the terms of the GPLv3.
@@ -77,17 +77,17 @@ mxlw=100; test ${LINEWIDTH:=66} -gt $mxlw && LINEWIDTH=$mxlw
 
 cleanup() {
 	rc=$?
-	local t
 	for t in "$T1" "$T2"
 	do
-		test -n "$t" && rm -- "$t"
+		test "$t" && rm -- "$t"
 	done
-	test $rc = 0 || echo "$APP failed!" >& 2
+	test $rc = 0 || echo "\"$APP\" failed!" >& 2
 }
 APP=${0##*/}
 T1=
 T2=
 trap cleanup 0
+trap 'exit $?' HUP INT TERM QUIT
 sep=`
 	dd if=/dev/zero bs=1 count="$SEPARATOR_CHARS_IN_SEPARATOR" \
 		2> /dev/null \
diff --git a/screenshot-for-the-poor b/screenshot-for-the-poor
--- a/screenshot-for-the-poor
+++ b/screenshot-for-the-poor
@@ -14,16 +14,15 @@
 # "libnotify-bin" package. (Those package names refer to Debian-based
 # distributions).
 #
-# Version 2021.316
-#
-# Copyright (c) 2013-2021 Guenther Brunthaler. All rights reserved.
+# Version 2023.211
+# Copyright (c) 2013-2023 Guenther Brunthaler. All rights reserved.
 #
 # This script is free software.
 # Distribution is permitted under the terms of the GPLv3.
 
 cleanup() {
-	test -n "$T" && rm -- "$T"
-	test -n "$OK" || notify-send -i error -t 10000 "$APP failed!"
+	test "$T" && rm -- "$T"
+	test "$OK" || notify-send -i error -t 10000 "$APP failed!"
 }
 
 set -e
@@ -31,6 +30,7 @@ APP=${0##*/}
 OK=
 T=
 trap cleanup 0
+trap 'exit $?' HUP INT TERM QUIT
 WINDOW=
 while getopts w OPT
 do
@@ -40,7 +40,7 @@ do
 	esac
 done
 shift `expr $OPTIND - 1 || :`
-if test -n "$WINDOW"
+if test "$WINDOW"
 then
 	m="Screenshot: Select a window by clicking into it!"
 	notify-send -i info -t 3000 "$m"
diff --git a/stitch-flat-scanned-images b/stitch-flat-scanned-images
--- a/stitch-flat-scanned-images
+++ b/stitch-flat-scanned-images
@@ -1,9 +1,8 @@
 #! /bin/sh
 exit_version() {
 	cat << EOF | wrs; exit
-$APP version 2019.334
-
-Copyright (c) 2015-2019 Guenther Brunthaler. All rights reserved.
+$APP version 2023.211
+Copyright (c) 2015-2023 Guenther Brunthaler. All rights reserved.
 
 This script is free software.
 Distribution is permitted under the terms of the GPLv3.
@@ -81,15 +80,16 @@ EOF
 set -e
 cleanup() {
 	rc=$?
-	test -n "$TD" && rm -rf -- "$TD"
-	test $rc = 0 || echo "$0 failed!" >& 2
+	test "$TD" && rm -rf -- "$TD"
+	test $rc = 0 || echo "\"$0\" failed!" >& 2
 }
 TD=
 trap cleanup 0
+trap 'exit $?' HUP INT TERM QUIT
 
 if
 	test -t 0 && LINEWIDTH=`tput cols 2> /dev/null` \
-	&& test -n "$LINEWIDTH"
+	&& test "$LINEWIDTH"
 then
 	MAX=100
 	test $LINEWIDTH -gt $MAX && LINEWIDTH=$MAX
@@ -134,7 +134,7 @@ for tool in \
 	pano_modify hugin_executor pto_gen pto_lensstack pto_var
 do
 	x=`which -- "$tool"`
-	test -n "$x"; test -f "$x"; test -x "$x"
+	test "$x"; test -f "$x"; test -x "$x"
 	eval "$tool=\$x"
 done
 
@@ -156,10 +156,10 @@ do
 		-compress LZW "$TD/$of"
 	"$identify" -format '%x %y %U\n' "$TD/$of" > "$TD/ii.txt"
 	read n_xres n_yres n_resunits < "$TD/ii.txt"
-	test -n "$n_xres"
-	test -n "$n_yres"
-	test -n "$n_resunits"
-	if test -n "$resunits"
+	test "$n_xres"
+	test "$n_yres"
+	test "$n_resunits"
+	if test "$resunits"
 	then
 		test x"$n_xres" = x"$xres"
 		test x"$n_yres" = x"$yres"
@@ -171,7 +171,7 @@ do
 	bf=${f##*/}; cfp=$cfp${cfp:++}${bf%.*}
 	nf=`expr $nf + 1`
 done
-test -n "$cfp"
+test "$cfp"
 test -z "$outfile" && outfile=$cfp.tif
 
 Prefix=out
diff --git a/tmpdir-shell b/tmpdir-shell
--- a/tmpdir-shell
+++ b/tmpdir-shell
@@ -1,27 +1,28 @@
 #! /bin/sh
 # Run a shell in a temporary directory to be removed when the shell exits.
-# Version 2021.89
+# Version 2023.211
 
 set -e
 cleanup() {
 	rc=$?
 	cd
-	if test -n "$T"
+	if test "$T"
 	then
 		find "$T" -xdev ! -type d -exec rm -f -- {} +
 		find "$T" -xdev -depth -type d -exec rmdir -- {} +
 	fi
-	test $rc = 0 || echo "$APP failed!" >& 2
+	test $rc = 0 || echo "\"$APP\" failed!" >& 2
 }
 APP=${0##*/}
 T=
 trap cleanup 0
-T=`mktemp -d "${TMPDIR:-/tmp}/$APP.XXXXXXXXXX"`
+trap 'exit $?' HUP INT TERM QUIT
+T=`mktemp -d -- "${TMPDIR:-/tmp}/$APP.XXXXXXXXXX"`
 echo "Entering temporary shell directory '$T'." >& 2
-p=`pwd`
+p=$PWD
 echo "The previous current directory is available as \$p." >& 2
 echo "Enter 'exit' to leave and remove temporary directory." >& 2
-cd "$T"
+cd -- "$T"
 PS1='\u@\h [tmpshell] \$ ' # Most likely, this will be overwritten anyway.
 export PS1 p
 case ${SHELL:=/bin/sh} in
