Remove -v option and make it implicit
The conversion will always be pumped through two additional pipes: One
converting it to LATIN-9 and a second one to convert it back.

Errors in all stages of the pipeline will be detected and cause the
script to fail.

diff --git a/latin9ize-unicode-text b/latin9ize-unicode-text
--- a/latin9ize-unicode-text
+++ b/latin9ize-unicode-text
@@ -12,25 +12,60 @@
 # Distribution is permitted under the terms of the GPLv3.
 
 set -e
-trap 'test $? = 0 || echo "$APP failed in line $lnum!" >& 2' 0
 
-show_pos() {
-	crad=10 # default context radius
-	shift; OPTIND=1
-	pos=
-	while getopts p:c: opt
+pipelines_wait() {
+	local worst rc pid
+	worst=0
+	for pid in $BG_PIDS
 	do
-		case $opt in
-			p) pos=$OPTARG;;
-			c) crad=$OPTARG
-		esac
+		wait $pid && continue
+		rc=$?
+		test $rc -gt $worst && worst=$rc
 	done
-	shift $OPTIND
+	BG_PIDS=
+	(exit $worst)
+}
+
+pipelines_kill() {
+	local restore signal
+	restore=`trap`;	signal=${1-TERM}
+	trap '' $signal; kill -$signal 0
+	eval "$restore"
+	pipelines_wait
+}
+
+cleanup() {
+	rc=$?
+	pipelines_kill || :
+	test "$TD" && rm -r -- "$TD"
+	test $rc = 0 || echo "$0 failed!" >& 2
+}
+TD=
+BG_PIDS=
+trap cleanup 0
+trap 'exit $?' INT TERM QUIT HUP
+
+verify_posint_arg() {
+	expr x"$OPTARG" : x'[1-9][0-9]*$' > /dev/null
+}
+
+opts=
+crad=10 # Context radius.
+pos=
+while getopts ip:c: opt
+do
+	case $opt in
+		i) opts="$opts -$opt";;
+		p) verify_posint_arg; pos=$OPTARG;;
+		c) verify_posint_arg; crad=$OPTARG;;
+		*) false || exit
+	esac
+done
+shift `expr $OPTIND - 1 || :`
+
+if test "$pos"
+then
 	test $# = 0 && set /dev/stdin
-	for pint in "$pos" "$crad"
-	do
-		expr x"$pint" : x'[1-9][0-9]*$' > /dev/null
-	done
 	cbef=`expr $crad \& $pos \> $crad \| $pos || :`
 	cdia=`expr $cbef + $crad`
 	rbs=8192
@@ -46,23 +81,43 @@ show_pos() {
 	` 2> /dev/null
 	pfx=`printf '%s\n' "$lb" | dd bs=1 count=$cbef` 2> /dev/null
 	echo "<...>$pfx<AFTER_THIS>${lb#"$pfx"}<...>"
+	exit
+fi
+
+TD=`mktemp -d -- "${TMPDIR:-/tmp}/${0##*/}".XXXXXXXXXX`
+
+get_fifo() {
+	case $2 in
+		"" | +)
+			eval fifo=\$NX_FIFO_$1
+			case $2 in
+				+) fifo=`expr $fifo + 1`
+			esac
+			;;
+		*) fifo=$2
+	esac
+	eval NX_FIFO_$1=\$fifo
+	fifo=$TD/$1_$fifo
+	test -e "$fifo" && return
+	mkfifo -- "$fifo"
 }
 
-opts=
-wrapper=
-while getopts vip:c: opt
-do
-	case $opt in
-		v) wrapper='verify ';;
-		i) opts="$opts -$opt";;
-		[pc]) opts="$opts -$opt $OPTARG"; wrapper='show_pos ';;
-		*) false || exit
-	esac
-done
-shift `expr $OPTIND - 1 || :`
+pipeline_start() {
+	local fifo
+	get_fifo "$1" 1; shift
+	"$@" > "$fifo" & BG_PIDS="$! $BG_PIDS"
+}
 
-verify() {
-	"$@" | iconv -t LATIN9 > /dev/null
+pipeline_cont() {
+	local lfifo fifo
+	get_fifo "$1"; lfifo=$fifo; get_fifo "$1" +; shift
+	"$@" < "$lfifo" > "$fifo" & BG_PIDS="$! $BG_PIDS"
+}
+
+pipeline_complete() {
+	local fifo
+	get_fifo "$1"; shift
+	"$@" < "$fifo" & BG_PIDS="$! $BG_PIDS"
 }
 
 substs=`
@@ -78,4 +133,7 @@ y/+A7w-/+ALU-/
 y/+AUIBGQEfAQ0BRA-/legcn/
 EOF
 `
-${wrapper}sed$opts "$substs" "$@"
+pipeline_start 1 sed$opts "$substs" "$@"
+pipeline_cont 1 iconv -t LATIN9
+pipeline_complete 1 iconv -f LATIN9
+pipelines_wait
