Add code-size, ctime- and RAM-usage reporters
"code-sizes-of-pid" examines the process image of a running process and
reports all executable files mapped into its address space. If the
option -X is provided, any files mapped will be reported and not just
executables. The apparent sizes (not ignoring any sparse sections) of
the reported files will also be shown, along with the total of all file
sizes.

"ls-ctimes-sizes" shows the inode change time and the byte size for
specified files, one file per line. This is useful as a quick check
whether some files might have changed, before doing expensive operations
on them like recalculating their hashes.

"ram-used-by-running-instances-of-program" did already exist, but
improve it to report on more than one command or on all running commands
if no command names are specified as arguments.

diff --git a/ram-used-by-running-instances-of-program b/ram-used-by-running-instances-of-program
--- a/ram-used-by-running-instances-of-program
+++ b/ram-used-by-running-instances-of-program
@@ -1,7 +1,91 @@
 #! /bin/sh
-# v2024.54
+
+# Provide command names of running processes. Outputs a report about their RAM
+# usages. Without any arguments, shows the usage of all running processes.
+#
+# v2024.100
+
+set -e
+trap 'test $? = 0 || echo "\"$0\" failed!" >& 2' 0
+
+while getopts '' opt
+do
+	case $opt in
+		*) false || exit
+	esac
+done
+shift `expr $OPTIND - 1 || :`
+
+decimal_point=.
+eval "`locale -k LC_NUMERIC | grep ^decimal_point=`" 2> /dev/null
 ps -Ao comm,rss \
-| awk -v p="${1:?command name of instances}" '
-	$1 == p {k += $2; ++i}
-	END {printf "%d x %s = %.1f MiB RAM\n", i, p, k / 1024}
-'
+| awk -v dp="$decimal_point" -v p="$*" -f /dev/fd/5 5<< 'EO_AWL'
+
+{
+	k[$1] += $2 # k[]: Total RAM used by all commands of the same name.
+	++i[$1] # i[]: Number of running instances associated with k[].
+}
+
+END {weed_unrequested(); weed_irrelevant(); report()}
+
+# Report RAM usage per command group (all running instances), sorted by
+# decreasing RAM usage first, then by decreasing number of instances.
+function report(    j, j2, n, u, q, t) {
+	# Create lookup-array u[].
+	n = 0; for (j in k) u[n++] = j
+	# Sort u[] descending by k[j] then descending by i[j] then ascending
+	# by j. u[] contains the j.
+	#
+	# Gnomesort: Invariant is that u[0 ... q] are already sorted.
+	for (q = 0; q + 1 < n; ) {
+		# Compare u[q] and u[q + 1].
+		j = u[q]; j2 = u[q + 1]
+		if ((t = k[j2] - k[j]) == 0) {
+			if ((t = i[j2] - i[j]) == 0) {
+				t = j <= j2 ? -1 : 1
+			}
+		}
+		# Are u[q] and u[q + 1] already in correct sorting order?
+		if (t >= 0) {
+			# No. Swap u[q] and u[q + 1] into sorting order.
+			t = u[q]; u[q] = u[q + 1]; u[q + 1] = t
+			# Then move to the left if possible, otherwise to the
+			# right.
+			if (q) {--q; continue}
+		}
+		# Yes, the are in sorting order. Include element to the right
+		# into the already-sorted sequence.
+		++q
+	}
+	# Report command groups in sorting order.
+	for (q = 1; u[q]; ++q) {
+		j = u[q]
+		t = sprintf("%.1f", k[j] / 1024)
+		gsub("[.]", dp, t)
+		printf "%d x %s = %s MiB RAM\n", i[j], j, t
+	}
+}
+
+# Remove all entries from k[x] and i[x] where x is not a word within p.
+function weed_unrequested(    a, j, ok) {
+	if (p == "") return
+	split(p, a, " ")
+	for (j in a) if (k[j]) ok[a[j]] = 1
+	for (j in k) {
+		if (!(j in ok)) {
+			delete k[j]; delete i[j]
+		}
+	}
+}
+
+# Remove any entries for which the RAM usage has been reported as 0 (these are
+# typically kernel threads).
+function weed_irrelevant(    j) {
+	for (j in k) {
+		if (k[j] == 0) {
+			delete k[j]; delete i[j]
+		}
+	}
+}
+
+EO_AWK
