Upgrade secure SSH key generator
Because commit

https://github.com/torvalds/linux/commit/30c08efec8884fb106b8e57094baa51bb4c44e32

ruined /dev/random as a reliable source of random key material, I
updated my secure version of ssh-keygen by combining three sources of
random numbers for key creation: /dev/urandom, haveged and (if present)
bytes from the hardware random number generator /dev/hwrng.

If only one of those sources generates random numbers with entropy, the
generated keys should be secure.

Actually, haveged alone should alway generate such random numbers with
full entropy, but it might have implementation flaws or overestimate the
amount of entropy it returns. Therefore, mixing with bytes obtained from
/dev/urandom will make it as least as secure as the latter one, which
the original ssh-keygen will also use. Which means, in the worst case we
are no better than the original, but never inferior to that.

One problem however is that the current Debian 11 version of haveged has
a bug so that it cannot be used with the new ssh-keygen-openssl version
if another instance of haveged is running.

If you encounter this problem, you can resolve it as follows:

1. Upgrade to a newer version of haveged which does no longer have that
bug.

2. Temporarily stop the haveged daemon. Then the script will propably
work.

3. Build a private version of haveged and install the patch I have sent
to upstream as well as to the Debian Mailing list. Basically it just
changes a single source line.

Here is a copy:

--- haveged-1.9.14.orig/src/haveged.c
+++ haveged-1.9.14/src/haveged.c
@@ -429,7 +429,7 @@ int main(int argc, char **argv)
       close(socket_fd);
       return ret;
       }
-   else {
+   else if (!(params->setup & RUN_AS_APP)){
       socket_fd = cmd_listen(params);
       if (socket_fd >= 0)
          fprintf(stderr, "%s: command socket is listening at fd %d\n", params->daemon, socket_fd);

diff --git a/ssh-keygen-openssl b/ssh-keygen-openssl
--- a/ssh-keygen-openssl
+++ b/ssh-keygen-openssl
@@ -1,9 +1,9 @@
 #! /bin/sh
 exit_version() {
 	wr -s << . && exit
-$APP version 2018.183
+$APP version 2021.306
 
-Copyright (c) 2018 Guenther Brunthaler. All rights reserved.
+Copyright (c) 2018-2021 Guenther Brunthaler. All rights reserved.
 
 This script is free software.
 Distribution is permitted under the terms of the GPLv3.
@@ -27,19 +27,33 @@ numbers from /dev/urandom may be of poor quality, deterministic or even be
 completely predictable.
 
 $APP emulates ssh-keygen's behaviour regarding key generation, but uses
-/dev/random for gathering the required random bytes. Contrary to /dev/urandom,
-/dev/random always returns high-quality random numbers with sufficient entropy
-- which is exactly what one usually wants for cryptographic keys.
+entropy harvested by the "haveged" executable (which must be installed but
+does not need to be running as a daemon) for gathering the required random
+bytes. For additional security, it also requests the same amount of random
+numbers from /dev/urandon and mixes it with the entropy gathered by hageged.
 
-However, there is a caveat when using /dev/random: If will block as long as it
-takes to generate high-quality random numbers, which may be a really long
-time.
+This should result in high-quality random numbers with full entropy - which is
+exactly what one usually wants for cryptographic keys.
 
-Therefore it is recommended to install package "rng-tools" (for feeding data
-from a hardware random number generator into /dev/random), "haveged" (if no
-hardware RNG is available, it feeds CPU/cache timing variations into
-/dev/random), or some other kind of entropy gathering daemon before running
-$APP.
+(As a historic note, /dev/random also used to retrieve such high-quality
+random numbers once. But a change made to the Linux kernel in 2020 effectively
+ruined /dev/random, making it no better than and basically the same as
+/dev/urandom.)
+
+As an option, one might to consider installing package "rng-tools" if the
+local platform has a random number generator. If installed, its daemon will
+feed entropy from the hardware random number generator to the kernel, which
+will at least improve (but not enough to ensure entropy) the quality of
+/dev/urandom.
+
+As an alternative to "rng-tools" for systems without a hardware random number
+generator, consider running "haveged" as a daemon. It will also feed entropy
+into the kernel and improve the quality of /dev/urandom, but like rng-tools it
+cannot fix the damage done to /dev/random in 2020 either.
+
+Note that running the "rng-tools" or "haveged" daemons is indeed optional -
+$APP will use haveged directly as an executable in any case for gathering
+entropy, whether it is running as a daemon or not.
 
 Options:
 
@@ -138,13 +152,84 @@ do
 done
 shift `expr $OPTIND - 1 || :`
 
+verify_installed() {
+	pkg=
+	missing=false
+	for needed
+	do
+		case $needed in
+			*:) pkg=${needed%:};;
+			*)
+				command -v "$needed" > /dev/null 2>& 1 \
+					&& continue
+				echo "Required utility '$needed' is" \
+					" missing!" >& 2
+				echo "On some systems, it may be installed" \
+					" with:" >& 2
+				printf '$ ' >& 2
+				echo "sudo apt-get install $pkg"
+				echo >& 2
+				missing=true
+		esac
+	done
+	if $missing
+	then
+		echo "Please install the missing packages," \
+			" then try again!" >& 2
+		false || exit
+	fi
+}
+
+# Ensure we can find "haveged", even if it is only in root's $PATH.
+PATH=/usr/local/sbin:/usr/sbin:/sbin:/opt/sbin:$PATH
+
+verify_installed \
+	haveged: haveged \
+	openssh-client:	ssh-keygen \
+	openssl: openssl \
+
+if $ppk_gen
+then
+	verify_installed putty-tools: puttygen
+fi
+
 for n
 do
 	test "$n"
 	test -d "`dirname -- "$n"`"
 done
 
-TDIR=`mktemp -d "${TMPDIR:-/tmp}/$APP".XXXXXXXXXX`
+TDIR=`mktemp -d -- "${TMPDIR:-/tmp}/$APP".XXXXXXXXXX`
+
+# Gather a block of $1 (no more than 32) full-entropy random bytes.
+gather_entropy_block() {
+	{
+		{
+			dd if=/dev/urandom bs=1 count="$1"
+			haveged -f - -n "$1"
+			hr=/dev/hwrng
+			if test -r "$hr" && test -c "$hr"
+			then
+				dd if="$hr" bs=1 count=32
+			fi
+		} | openssl sha256 -binary | dd bs="$1" count=1
+	} 2> /dev/null
+}
+
+# Harvest the specified number of entropy bytes and write them to standard
+# output in binary form.
+gather_entropy_bytes() {
+	left=$1
+	while test "$left" -ge 32
+	do
+		gather_entropy_block 32
+		left=`expr $left - 32 || :`
+	done
+	case $left in
+		0) ;;
+		*) gather_entropy_block "$left"
+	esac
+}
 
 # Calculate additional bytes of entropy to provide for the last openssl
 # invocation. This will be used to "re-charge" openssl's randomness seeding
@@ -184,8 +269,8 @@ do
 		# This will be the last invocation of openssl by this script.
 		e=`expr $e + $recharge_seeding_bytes`
 	fi
-	echo "Collecting $e bytes of entropy..." >& 2
-	dd if=/dev/random bs=1 count="$e" of="$TDIR"/rnd
+	echo "Collecting $e bytes of entropy (may take a few seconds)..." >& 2
+	gather_entropy_bytes "$e" > "$TDIR"/rnd
 	openssl genrsa -out "$t".prv -rand "$TDIR"/rnd "$bits"
 	chmod 600 -- "$t".prv
 	ssh-keygen -yf "$t".prv > "$t".tmp
