Added verbosity option to text chat script

diff --git a/textchat b/textchat
--- a/textchat
+++ b/textchat
@@ -1,7 +1,7 @@
 #! /bin/sh
 show_version() {
 	cat <<- .
-	$APP version 12.108.3
+	$APP version 12.108.5
 
 	(c) 2012 by Guenther Brunthaler.
 	This source file is free software.
@@ -61,8 +61,12 @@ and "write" will be used to inform the client how to connect to the chat.
 -c <server2contact>: Client mode. Connect to an existing chat as a client,
 specifying the chat server's PTY device path as the argument.
 
--h: Display this help
--V: Display version info
+-v: Be verbose. Displays the actual commands being executed for implementing
+the chat.
+
+-h: Display this help.
+
+-V: Display version info.
 
 SECURITY CAVEAT:
 
@@ -139,13 +143,23 @@ msg2client() {
 }
 
 
+exit_usage() {
+	show_help
+	echo
+	show_version
+	test x$MODE = x"help"; exit
+}
+
+
 APP=${0##*/}
 MODE=
-while getopts cshV OPT
+VERBOSE=
+while getopts csvhV OPT
 do
 	case $OPT in
 		c) MODE=client;;
 		s) MODE=server;;
+		v) VERBOSE=Y;;
 		h) MODE=help;;
 		V) MODE=version;;
 		*) false; exit
@@ -158,10 +172,7 @@ if
 		test -z "$PEER" && test x$MODE != x"server"
 	}
 then
-	show_help
-	echo
-	show_version
-	test x$MODE = x"help"; exit
+	exit_usage
 elif test x$MODE = x"version"
 then
 	show_version
@@ -177,14 +188,19 @@ then
 	echo "by pressing ctrl-c.)"
 	echo
 	run test -c "$PEER"
+	test -n "$VERBOSE" && set -x
 	exec "$SOCAT" OPEN:$PEER,echo=0 READLINE,prompt='self> '
+	set +x
 	die "Could not exec $SOCAT to act as a chat client!"
 fi
+
 run test x$MODE = x"server"
 system tempfile; T=$REPLY
+trap "rm '$T'" 0
 trap 'false; exit' USR1
 PARENT=$$
 {
+	trap - 0
 	while :
 	do
 		test -e "$T" || exit
@@ -214,4 +230,7 @@ PARENT=$$
 	echo
 	trap - 0
 } &
-exec "$SOCAT" READLINE,prompt='self> ' PTY,link=$T
+test -n "$VERBOSE" && set -x
+exec "$SOCAT" READLINE,prompt='self> ' PTY,perm=666,link=$T
+set +x
+die "Could not exec $SOCAT to act as a chat server!"
