Make u2u-mkdir use perl bigints if there is no bc

diff --git a/u2u-mkdir b/u2u-mkdir
--- a/u2u-mkdir
+++ b/u2u-mkdir
@@ -367,28 +367,44 @@ wr() {
 	fi
 }
 
+print_rnd_uuid() {
+	if test -f "$UUID_SOURCE"
+	then
+		run cat "$UUID_SOURCE"
+	else
+		set -- $UUID_CMD
+		run "$@"
+	fi | run tr -d '-'
+}
 
 gen_uuid() {
-	{
-		echo "obase=35; ibase=16"
+	if test -n "$BC"
+	then
 		{
-			if test -f "$UUID_SOURCE"
-			then
-				run cat "$UUID_SOURCE"
-			else
-				set -- $UUID_CMD
-				run "$@"
-			fi
-		} | run tr -d '-' | LC_ALL=C run tr '[:lower:]' '[:upper:]'
-	} | LC_ALL=C POSIXLY_CORRECT=1 run bc \
-	| {
-		s=
-		while IFS= read -r line
-		do
-			s=$s${line%"\\"}
-		done
-		run printf '%s' "$s"
-	} | LC_ALL=C POSIXLY_CORRECT=1 run awk '
+			echo "obase=35; ibase=16"
+			print_rnd_uuid \
+			| LC_ALL=C run tr '[:lower:]' '[:upper:]'
+		} | LC_ALL=C POSIXLY_CORRECT=1 run "$BC" \
+		| {
+			s=
+			while IFS= read -r line
+			do
+				s=$s${line%"\\"}
+			done
+			run printf '%s' "$s"
+		}
+	else
+		run perl -Mbigint -we '
+			my $num= 0x'"`print_rnd_uuid`"';
+			my @b35;
+			do {
+				push @b35, $num % 35;
+				$num/= 35;
+			} while $num != 0;
+			print join " ", reverse @b35;
+		'
+	fi \
+	| LC_ALL=C POSIXLY_CORRECT=1 run awk '
 		{
 			alphabet= "0123456789abcdefghijklmnpqrstuvwxyz"
 			out= ""
@@ -440,6 +456,10 @@ SYMLINK_OPTIMIZER_ARGS=-q
 APP=${0##*/}
 # Determine output line width.
 LINEWIDTH=; REPLY=; test -t 1 && system tput cols; LINEWIDTH=${REPLY:-70}
+# We need big integers support.
+BC=`which bc 2> /dev/null` && test -x "$BC" \
+|| test x`perl -Mbigint -e 'print 1 << 128' 2> /dev/null | wc -c` = x39 \
+|| die "bc or perl with bigint support are required!"
 # Start of command line processing.
 # Define presets.
 VERBOSE=
