Support some long options in additon to short ones
What still does not work is the --option=value syntax. "--option value"
should already work, though. (Not tested yet.)

diff --git a/wget-offline-faker b/wget-offline-faker
--- a/wget-offline-faker
+++ b/wget-offline-faker
@@ -1,7 +1,7 @@
 #! /bin/sh
 exit_version() {
 	wr -s << ===; exit
-$APP Version 2021.280.2
+$APP Version 2021.296
 
 Copyright (c) 2021 Guenther Brunthaler. All rights reserved.
 
@@ -35,26 +35,8 @@ $ ln -s "\`command -v $APP\`" wget
 Otherwise, you need to explicitly specify where the "$APP" resides when
 creating the symlink.
 
-Alternatively, create a stub script in the download directory invoking "$APP"
-like this:
-
-===
-	cat << '==='
-$ cat > wget << 'EOF' && chmod +x wget
-#! /bin/sh
-exec wget-offline-faker -P :"$0" ${1+"$@"}
-EOF
-
-===
-	wr << ===
-An argument of option "-P" starting with ":" is intercepted by "$APP" in order
-to provide the path of the stub script. This path needs to be known by "$APP"
-when it is exec'ed by the stub script for locating the download directory. This
-is not necessary when a symlink is used rather than the stub script.
-
-After creating the symlink or stub script, make sure that the download
-directory has been put within \$PATH before the directory where the real
-"wget" can be found.
+After creating the symlink, make sure that the download directory has been
+put within \$PATH before the directory where the real "wget" can be found.
 
 This can then be used to trick scripts which invokes "wget" to actually use
 "$APP" instead, therefore redirecting the downloads from the files in the
@@ -101,10 +83,12 @@ there which actually points to "$APP".
 
 Then change into that directory and excute the following commands
 
-$ eval "`apt-config shell opath DPkg::Path`"
 ===
 	wr << '==='
-$ set -- -o DPkg::Path "$PWD:$opath"; unset opath
+$ eval "`apt-config shell opath DPkg::Path`"; xp=$PWD
+===
+	wr << '==='
+$ set -- -o DPkg::Path="$xp:$opath"; unset opath
 
 Then use "$@" as additional options when invoking "apt" or "apt-get" in your
 command line, i. e.
@@ -123,11 +107,11 @@ This allows offline-installation of package firmware-b43-installer and
 similar package downloaders which would otherwise not be supported because
 they invoke wget directly in their postinstallation scripts.
 
-The above "set" command will also set $3 to the proper $PATH containing the
-fake "wget" symlink, which needs to be set for "dpkg" and "dpkg-reconfigure"
-in order to make use of the fake downloader. For instance,
+The above commandw will also set $xp to the proper $PATH containing the fake
+"wget" symlink, which needs to be set for "dpkg" and "dpkg-reconfigure" in
+order to make use of the fake downloader.  For instance,
 
-$ PATH=$3 sudo dpkg-reconfigure rocksndiamonds
+$ PATH=$xp sudo dpkg-reconfigure rocksndiamonds
 ===
 	echo; exit_version
 }
@@ -164,6 +148,11 @@ LINEWIDTH=`
 set -e
 trap 'test $? = 0 || echo "\"$0\" failed!" >& 2' 0
 
+die() {
+	printf "ERROR: %s\n" "$*" >& 2
+	false || exit
+}
+
 # Protect arguments from shell by quoting, but only if necessary.
 qin() {
 	#local arg out
@@ -181,60 +170,42 @@ qin() {
 	printf '%s\n' "$out"
 }
 
-# Build original command string, but filter out -P options starting with ":"
-# because this script will use such options for itself for overriding the
-# script path within the offline download directory.
-filter_args() {
-	args=
-	opt_P=false
-	for opt
-	do
-		case $opt_P in
-			true)
-				opt_P=false
-				case $opt in
-					:*) continue
-				esac
-				args="$args -P"
-		esac
-		case $opt in
-			-P:*) continue;;
-			-P) opt_P=true;;
-			*) args="$args `qin "$opt"`"
-		esac
-	done
-	printf '%s\n' "$args"
-}
-
-ocmd=`filter_args ${1+"$@"}`
 cont=false
 more=true
 out=
 opfx=.
 script=$0
 fixer=download_missing_files.sh
-while getopts cO:P:hV opt
+ocmd=
+copts=
+while :
 do
-	case $opt in
-		P)
-			case $OPTARG in
-				:?*)
-					script=${OPTARG#:}
-					test -f "$script"
-					;;
-				*)
-					test -d "$OPTARG"
-					opfx=$OPTARG
-			esac
-			;;
-		c) cont=true;;
-		O) test "$OPTARG"; out=$OPTARG;;
-		h) exit_help;;
-		V) exit_version;;
-		*) false || exit
+	if test -z "$copts"
+	then
+		case $1 in
+			-?*) copts=$1; shift;;
+			*) break
+		esac
+	fi
+	if test "${copts#--}" = "$copts"
+	then
+		tail=${copts#-?}; # Switch clustering.
+		copt=${copts%"$tail"}; copts=${tail:+-}$tail
+	else
+		copt=$copts; copts=
+	fi
+	# Any arguments are at $1 and onwards; must be shifted off.
+	case $copt in
+		--) break;; # Must be first!
+		--directory-prefix | -P) test -d "$1"; opfx=$1; shift;;
+		--continue | -c) cont=true; ocmd="$ocmd -c";;
+		--output-document | -O) test "$1"; out=$1; shift;;
+		--timeout | -T) ocmd="$ocmd -T$1"; shift;;
+		--help | -h) exit_help;;
+		--version | -V) exit_version;;
+		*) die "Unknown option '$copt'!";; # Must be last!
 	esac
 done
-shift `expr $OPTIND - 1 || :`
 
 ocmd=wget$ocmd
 case $script in
