Allow to specify output font size for xclock

diff --git a/xclock-big-HHMMSS b/xclock-big-HHMMSS
--- a/xclock-big-HHMMSS
+++ b/xclock-big-HHMMSS
@@ -1,3 +1,23 @@
 #! /bin/sh
+size=50
+
+set -e
+trap 'test $? = 0 || echo "$0 failed!" >& 2' 0
+
+while getopts '' opt
+do
+	case $opt in
+		*) false || exit
+	esac
+done
+shift `expr $OPTIND - 1 || :`
+
+if test $# = 1
+then
+	expr x"$1" : x'[1-9][0-9]*$' > /dev/null
+	size=$1
+fi
+
 cd /
-xclock -digital -update 1 -strftime %T -face "Times New Roman-50" &
+xclock > /dev/null 2>& 1 < /dev/null \
+	-digital -update 1 -strftime %T -face "Times New Roman-$size" &
